### ISSUE TITLE
Add link to IRC / Riot in readme

### ISSUE THREAD

**Issue by freemo** [opennars/opennars#103]
to better facilitate communication between members lets consider creating a Gitter or Slack chatroom. I recommend Gitter since it is free and doesnt require a paid account, just need a github account.

Once created we should link to it with a gitter badge from the readme.

If we want to stick with IRC / Riot then we should add that link to the readme at least.

**Comment by patham9** [comment]
We already use riot.im actively as a "IRC Client with benefits" for the #nars room. Not sure about Gitter (don't know about it) but I would surely never switch to a closed-source solution such as Slack here.

**Comment by freemo** [comment]
I dont like slack either, so I'm with you on that. I used riot.im before,
not a fan, but not opposed to using it. Gitter is just more popular and
integrated with GitHub so may be worth considering.

**Comment by freemo** [comment]
If you guys decide you want to stick with IRC we should close this ticket and create a new one to add the info to the readme.

**Comment by TonyLo1** [comment]
I like Gitter but it is something else we will have to monitor. I suggest that we review our position on this in 3 months time. This will allow us to see what impact the current project changes have on the contributor base.

**Comment by TonyLo1** [comment]
ok - there are a few changes required to the READ.ME so I will consolidate and do one commit later today. I'll leave this open until I merge the changes.

**Comment by patham9** [comment]
this was already added.
