### ISSUE TITLE
Remove references to code.google.com

### ISSUE THREAD

**Issue by freemo** [opennars/opennars#109]
There are referneces in the readme and elsewhere to code.google.com. Correct me if im wrong but that site has since shutdown and old content is kept for archival purposes only. We should remove any old links to code.google.com that no longer make sense (like project status in the readme). The stuff we want to keep of course needs to be migrated so keeping a reference to such stuff elsewhere makes sense, but not in the readme.

**Comment by patham9** [comment]
the link on github was changed already, but this issue will be re-opened in case more of such links will be found, in the code etc.
