### ISSUE TITLE
Online Help / Tutorial App

### ISSUE THREAD

**Issue by automenta** [opennars/opennars#11]
simple 1-window application for learning NAL/NARS:

sidebar has a tree of unit tests organized by NAL level, gathered form nal/test files.  when clicked, they open it as an example showing the inputs, their english meaning (in comments), and expected output.  NAR executes this and shows the output.  the entire example can be analyzed and each statement can be graphed using the statement graph viewer.  this will help people to learn how the various NARS features work because they can go through each example and see it in action, at every step of the execution.

this app can also include the wiki pages, serving as an online help system and self-contained NARS course.

**Comment by patham9** [comment]
Similar functionality was added by Seth, the so called "Library panel". Comments in nal files show in the output GUI, and a variety of test case nal files can be selected and loaded.
