### ISSUE TITLE
Remove all binaries (libs) from GitHub history.

### ISSUE THREAD

**Issue by freemo** [opennars/opennars#112]
Binaries should have never been added to github and doesnt play well with git in general. By their nature they inflate the size of the repo and anyone who downloads the repo needs to download a much bigger set of files than they otherwise would have to (since a clone pulls down every binary ever added throughout history including every version).

I suggest we archive the original OpenNars repo as it is now so it is preserved, and then once mavenization is complete we cleanse history and remove all binaries through history. This lets us preserve history in git in terms of source changes without having hte binaries pollute the repo, but still lets us retrieve older copies of the source with the libraries from the archived repo.

**Comment by TonyLo1** [comment]
I'm all for this - I like to work with a minimal set of clean code.

**Comment by patham9** [comment]
I fully agree.

**Comment by freemo** [comment]
Ok let me merge in my mavenization stuff and splitting the repos, then lets get Tony's PR in, then i will do this ticket (since it will break the fast-forward). Then we will have a good foundation to refactor on top of.

**Comment by freemo** [comment]
This is now complete. Repo size went from ~130 MB down to ~8MB
