### ISSUE TITLE
contexts/namespaces via literal prefixes

### ISSUE THREAD

**Issue by automenta** [opennars/opennars#12]
investigate the possibility of implementing multiple namespaces/contexts within NARS through an optional literal naming convention involving a prefix code.  the presence of a prefix would automatically imply inheritance, product, and/or intensional set relationship between the prefix's concept and its contents.  subspaces can be defined by appending prefixes.

example, if '.' used to indicate contexts:
- namespace.item1
- namespace.item2
- namespace.subnamespace.item

this could be implemented either internally or through a macro pre-processor step

**Comment by jnorthrup** [comment]
seems like this is  relevaqnt to post-1.7

**Comment by patham9** [comment]
Something like namespaces can be realized by using products already, no syntax is needed for this.
```
(*,namespace,item1)
(*,namespace,item2)
(*,namespace,subnamespace,item)
Example:
<(*,(*,namespace,item1),{2}) --> value>.
<(*,(*,namespace,item2),{3}) --> value>.
<(*,(*,namespace,subnamespace,item),{3}) --> value>.
```
