### ISSUE TITLE
rename NAR to Nar

### ISSUE THREAD

**Issue by PtrMan** [opennars/opennars#172]
https://github.com/opennars/opennars/blob/master/src/main/java/org/opennars/main/NAR.java#L70

**Comment by TonyLo1** [comment]
Again, can you provide a code reference for those who are less familiar with the source

**Comment by freemo** [comment]
All instances of all capital names in classes and methods should be changed as well. Not to mention method names that start with a capital letter. But this is technically a dupicate, or at least related to #102 Basically checkstyle should enforce this rule and others.

**Comment by PtrMan** [comment]
https://github.com/opennars/opennars/pull/211 done
