### ISSUE TITLE
automate release process

### ISSUE THREAD

**Issue by automenta** [opennars/opennars#18]
set version, build .jar's, javadoc, website, upload

**Comment by jnorthrup** [comment]
i took a look at the source tree and i beleive i can make it a flat maven reactor project using mvn-terraform.

running ant on a 1 hour old ubuntu installation with jdk8 produces build errors https://gist.githubusercontent.com/anonymous/9304810d75f86c499b44/raw/opennarsfail 

does it help to collapse the build process to a maven hierarchy?  i wanted to see what rough edges could be addressed before i looked at interesting details like off-heap conversion soas to minimize the ripples of changing or refactoring across the packages 
before i looked at interesting details like off-heap conversion options and boost spirit narsese (which would avail itself nicely of misc.unsafe access)

**Comment by automenta** [comment]
volatile5 branch ("1.7") is already mavenized.  please try that one and see what you can recommend.  looking forward to your unique scalability solutions

**Comment by jnorthrup** [comment]
on the menu: 

source code formatter maven plugin  - the last word on indenting and tabstop disagreements in eclipse formatter xml? (Y/n)
versions-plugin - update everything to the latest versions, fix the api changes, rinse, repeat periodically?(Y/n)
camel-plugin, hawtio-plugins, basic camel container and mock junit test routes +- osgi +- jmx +- jms +- AMPQ +- etc. (y/n/Maybe)
generate pojos from (proto) IDL with maven plugin? (Y/n) 
opportuniistic insertion of APT-based AutoService,AutoValue,AutoFactory generators? (Y/n)

**Comment by jnorthrup** [comment]
im seeing shade in here.  shade collides META-INF/services say, for JDBC drivers etc.  things that each jarfile possess individually can get stomped.  

there is an alternative to shade at least for random hacking, which involves maven exec from commandline, or similar steps in a  shell script with maven-build-classpath.  proguard would share this limitation, but if its a closed loop of deps, then the META-INF can be hardcoded for the job at hand.  proguard is pretty sweet at trimming if META-INF is all sane after the merge
.

**Comment by automenta** [comment]
i was able to get this to work

https://github.com/chrischristo/capsule-maven-plugin

all the packaging plugins in there are entirely experimental

**Comment by automenta** [comment]
i didnt yet remove jackson-jr to be replaced by the more complete jaxb/camel solution  f0_EyPwvWTY json isnt used for anything critical yet, except for some output serialization

**Comment by jnorthrup** [comment]
another late-breaking option is to use <groupId>com.github.opennars</groupId> to follow the convention of jitpack.io ingestion

**Comment by automenta** [comment]
hopefully it doesnt require using the name "com.github.opennars"  the repo
needs mirrored to bitbucket, gitlab btw.  github policy has been known to
go sideways

**Comment by automenta** [comment]
all nars_util resources can be removed

**Comment by patham9** [comment]
v1.6.6 will include a script that does that, I won't handle release archives manually again.
And probably I will switch the project over to Gradle (or Maven), that way the Android and TeaVM build can just be another build target too.

**Comment by PtrMan** [comment]
I don't see how Android is sustainable in the future. NARS could/would use
tools which run only one "real" machines. With "real" machines I don't mean
potato computers like phones. Real machines have 10's or 100's of GB
RAM/SSD/HDD, GPU's, maybe FPGA's and so on and are fully customizable.

2017-10-24 13:04 GMT+02:00 patham9 <notifications@github.com>:

**Comment by patham9** [comment]
@ PtrMan: See LazyMiner ( https://groups.google.com/forum/#!topic/open-nars/B-IjA4uQ8wE )
It can lead to useful applications, smart phones are quite strong potatos already. 
But pervasive computing environments as a whole also have a lot of RAM and processors even when a single machine in the network doesn't have much of it. Multi-NAR applications can be an option too.
Since it comes with no cost for us, I don't mind supporting Android in the future too.

@automenta: Why was this issue closed??

**Comment by automenta** [comment]
the entire android API, being java, would be great to access in a general way via java reflection API.  the total system state (ex: battery life, running processes, notifications), sensors (accelerometer, gps, microphone, etc) and of course user input/applications are available to reason about.

it isnt clear what the advantage of introducing the LazyMiner term as opposed to "Mobile NARS" or something.  i wonder why ML ended up with the term "rule mining". i guess "pattern matching" just wasnt clear enough.  anyway maybe the strategy is to also confuse both cryptocurrency and minecraft users

**Comment by automenta** [comment]
(lazy) MyNAR

**Comment by automenta** [comment]
ie. Mobile (some word beginning with 'y') NAR

**Comment by patham9** [comment]
We can discuss this in IRC. ;)

**Comment by TonyLo1** [comment]
this has been resolved by tty1
