### ISSUE TITLE
complete webserver interface(s)

### ISSUE THREAD

**Issue by automenta** [opennars/opennars#19]
should have standard REST and WebSocket interface. improve UI design.

the REST interface will allow OpenNARS to be used as a component in websites

**Comment by jnorthrup** [comment]
i like both camel routes as netty endpoints equally as well with 1xio and bbcursive core io as a handoff to NARS pre-biased toward zero-copy IO that camel will never achieve.

**Comment by automenta** [comment]
is this relevant

https://github.com/undertow-io/undertow-io-site/blob/53e8c5bdb8c99d1d953c7d81d7d61ed0ad2295aa/documentation/faq.asciidoc#why-isnt-undertow-based-on-mina-netty-rnio-grizzly-or-insert-network-framework

**Comment by jnorthrup** [comment]
doesn't appear relevant to zero-copy - though i haven't dug in.  

undertow < camel i think in terms of sticking a piece of glue code in and getting a network service out. 

the web service benchmarks all show pretty close performance behind netty for most toolkit flavors.  "high performance" and "lightwieght" are implicit to anything that stands up. here again i dont see a distinction.

i hope that by projecting structs onto slabs the object count can be closer to a steady-state for a given thread and to make lazy access available for memoized references. 

1xio would hand nars a bytebuffer and set that as a basis for projecting structs on network buffers andemit getters and setters for interfaces

**Comment by automenta** [comment]
it will be an awesome but temporary solution until FIPA replaces HTTP

https://code.google.com/p/hypergraphdb/source/browse/trunk/p2p/src/java/org/hypergraphdb/peer/Performative.java#72

**Comment by automenta** [comment]
1988: http://en.wikipedia.org/wiki/Buran_programme#Missions
2000: http://en.wikipedia.org/wiki/Agent_Communications_Language
2015: HTTP REST

**Comment by automenta** [comment]
2013: http://en.wikipedia.org/wiki/QUIC

**Comment by jnorthrup** [comment]
post-1.7 

someone should restate issues relating to orthogonally away from middleware fabrics and more descriptive project elements for action potential, signalling,  actors, and usecases
