### ISSUE TITLE
save and load Memory as a perfectly serializable state

### ISSUE THREAD

**Issue by automenta** [opennars/opennars#21]
with unit tests that confirm it works

**Comment by patham9** [comment]
How would that ideally be implemented? If there is an easy way to get this done I will consider adding that. (or someone else could try, as I am currently concentrating on other things)

**Comment by automenta** [comment]
have a representation for everything in terms.  like TaskAsTerm. then be able to encode terms to binary like this

https://github.com/automenta/narchy/blob/skynet5/nal/src/main/java/nars/IO.java#L122
https://github.com/automenta/narchy/blob/skynet5/nal/src/main/java/nars/term/Term.java#L122

**Comment by automenta** [comment]
tasks = reified terms, tables = collection of tasks, memory = collection of tables.  read/write from an i/o stream which could be network or disk

**Comment by automenta** [comment]
what do you think about these rules
https://github.com/automenta/narchy/blob/skynet5/nal/src/main/resources/list.nal

in particular the ones like:
     (P-->C), (A ==> (Q-->C)), neq(Q,P), task("!") |- (substDiff(A, Q, P) ==>+- (P-->C)), (Punctuation:Question)

where substDiff substitutes the differing subterms between Q and P to transform A into some new compound that is related to P in the way that it was only related to Q

substDiff impl here:
https://github.com/automenta/narchy/blob/skynet5/nal/src/main/java/nars/Builtin.java#L53

note i'm using this as a question but it helps it find the missing associations between structures which can share common subterms but often do not due to the possibliity of variety

**Comment by pei2nars** [comment]
I don't fully understand the case. Is there a concrete example?

Regards,

Pei

**Comment by automenta** [comment]
vaguely like this:

x(intValue,(),3)! 1200 %1.0;.90% {1200: j}
(x(set,3)==>x(intValue,(),3))
x(set,4)@ 1200 {3604: k;;} (((%1-->%2),(%3==>(%4-->%2)),neq(%4,%1),task("!")),(substDiff(%3,%4,%1),((Quest-->Punctuation))))

"because A causes B, and i want X with outcome Y similar to B (ie. common extension) then maybe X transformed by the structural difference in B and A can achieve Y"

i can get an actual example soon though it suggests a category of rules with several permutations. if any one of them is useful then likely there are others

**Comment by patham9** [comment]
I don't get that example either, using original Narsese and not your butchered version of it would probably help too.  :)

**Comment by automenta** [comment]
it is an induction support rule

(^set, 0)!
(^set, 0).    feedback
(^get, 0)!
(^get, 0).    feedback
|-
((&/,(^set, 0),+1) ==> (^get, 0)).  temporal induction

(^set, 1)!

this is the point where i decided to add the rule, so that it could apply a learned example to a novel situation through a structural analogy.  the same kind which you could have applied in trying to understand my syntax.  

yes inducted rules containing variables can also eventually make the connection.  and images i guess but i am still fine without them.  this is a trivial example, but consider when multiple parameters of unknown variety are involved, possibly deeper within a compound

https://github.com/automenta/narchy/blob/skynet5/nal/src/main/java/nars/op/java/OObjects.java#L336

**Comment by automenta** [comment]
sorry what i meant was (^get, 1)! in that last line.  which would require the (^set, 1)! operation to be invoked.  but it has never done this before.  so this rule says:

(P-->C), (A ==> (Q-->C)), neq(Q,P), task("!") |- (substDiff(A, Q, P) ==>+- (P-->C)), (Punctuation:Question)
(^get, 1)!    +     ((&/,(^set, 0),+1) ==> (^get, 0)). 

it sees that what differs between Q=(0) and P=(1)  is the mapping 0:1 and then it substitutes this into A=(^set,0) producing (^set,1) to be used in a question or quest

**Comment by patham9** [comment]
Why was this issue closed? It's not yet realized..

Regarding the discussion: your rule isn't valid but I get the idea behind it.
Variable introduction captures that. OpenNARS would have no issue with making the jump from 0 to 1 here, not sure why that's not the case for your system.
You mentioned the temporal induction result
((&/,(^set, 0),+1) ==> (^get, 0)). temporal induction
which is just one result of temporal induction, but there should also be one with variable introduction:
((&/,(^set, $1),+1) ==> (^get, $1)). temporal induction
so that when
(^get, 1)!
is desired,
(^set, 1)! 
will be derived.

**Comment by automenta** [comment]
yes it can be solved (eventually) by variable introduction, especially deep variable introduction.  but it is not the same thing as variable introduction, its more like structural analogy introduction.

(P-->C), (A ==> (Q-->C)) |- (substDiff(A, Q, P) ==> (P-->C))
f(x(1), z(3))!
w(2) ==> f(x(1), y(2)).
w(3) ==> f(x(1), z(3))?

how many steps will this take with variable introduction and substitution of x(1) and 3? maybe minimum of two and if the subterms are more deeply embedded, also 2 i guess with deep variable introduction.  now consider where longer subterms are involved:

f(a, x, c, y, z)!
g(e, d, c, b, a) ==> f(a, b, c, d, e)
g(e, x, c, x, a) ==> f(a, x, c, y, z)?

**Comment by automenta** [comment]
```
f(a, x, c, x, z)!
g(e, d, c, b, a) ==> f(a, b, c, d, e)
g(e, x, c, x, a) ==> f(a, x, c, x, z)?
```

**Comment by automenta** [comment]
opennars can already save memory state.  so this issue is old

**Comment by patham9** [comment]
No idea where you got that from. Saving experience yes, but not saving the memory state.
Regarding the above: It's one step for variable introduction plus one step for deriving the subject of the implication.

**Comment by automenta** [comment]
if the parser is consistent with the text output then a text dump of the memory and re-input closes the issue.    you can continue to ignore the unit test requirements

**Comment by patham9** [comment]
Argh what just happened.. I wanted to edit my comment not delete yours, how can I undo this? Or can you re-type it? It was something like "If the parser can parse the toString representation then it can already do this, and that unit test requirements should be taken int account."

**Comment by patham9** [comment]
Anyways:
There is no toString() of memory, this is what needs to be coded. Also there is no parsing of such a representation to a memory object. There is a lot missing for that. This is why this issue exists.

Regarding unit tests: That's off-topic, but improving them is part of my plan for 1.6.6.

**Comment by automenta** [comment]
show me a wrong case please. https://github.com/automenta/narchy/tree/skynet5/nal/src/test/java/nars

**Comment by patham9** [comment]
Save/Load memory was easy to implement, I did it together with Tony and Robert today. 
Regarding your test cases, I will take the time to create issues for them in your repository.
