### ISSUE TITLE
Interface for Nar

### ISSUE THREAD

**Issue by PtrMan** [opennars/opennars#210]
Nar should implement the following interfaces

> IHasSensoryChannels
> \+ void addSensoryChannel(final String term, final SensoryChannel channel)

> IResetable
> \+ reset()

> IStringNarsese
> \+ boolean addMultiLineInput(final String text)
> \+ boolean addCommand(final String text)
> \+ void addInput(String text) 
> \+ void addInputFile(final String s)
> \+ NAR ask(final String termString, final AnswerHandler answered) throws InvalidInputException
> \+ NAR askNow(final String termString, final AnswerHandler answered)

ITaskConsumer
> \+ NAR addInput(final Task t)

> IEventable
> void on(final Class c, final EventObserver o)
> void off(final Class c, final EventObserver o)
> public void event(final EventObserver e, final boolean enabled, final Class... events)
> emit(final Class c, final Object... o)

>IHasPlugin
> void addPlugin(final Plugin p)
> void removePlugin(final PluginState ps)
> List<PluginState> getPlugins()

>IMultistepable
> void start(final long minCyclePeriodMS)
> void stop() 
> void cycles(final int cycles)
> void cycle()

INar should have the members
> \+ Concept concept(final String concept) throws InvalidInputException
> \+  public void run()
> \+ long time()
> \+ boolean isRunning() 
> \+ getMinCyclePeriodMS()
> \+ setThreadYield(final boolean b)

**Comment by freemo** [comment]
In java style interfaces do not begin with the letter `I`

**Comment by PtrMan** [comment]
https://github.com/opennars/opennars/pull/219

**Comment by PtrMan** [comment]
Completed
