### ISSUE TITLE
Handling of special Unicode

### ISSUE THREAD

**Issue by PtrMan** [opennars/opennars#250]
* some Unicode encodings look the same to humans but they fail to get parsed

**Comment by patham9** [comment]
can be seen as a duplicate of #249 right?
Wrong input such as usually coming from users shouldn't crash the system. Additionally information that shows "what went wrong" will be helpful.

**Comment by PtrMan** [comment]
Everything is a replicate to you

patham9 <notifications@github.com> schrieb am Sa., 19.05.2018, 0:05:
