### ISSUE TITLE
Separate Window for Answers to be listed

### ISSUE THREAD

**Issue by TonyLo1** [opennars/opennars#26]
Please can we have a separate window to display inference output answers. It is a real pain to have to keep scrolling up the output window to see if an answer has been found.

**Comment by patham9** [comment]
There is a volume level, if this one is low it will only show the answers and executions.

**Comment by patham9** [comment]
The "focus mode" was added for this purpose, better fitting what Tony wanted: In this mode only answers to user questions and executions show up.
