### ISSUE TITLE
Gain approval from contribs for License change to Apache

### ISSUE THREAD

**Issue by TonyLo1** [opennars/opennars#270]
As contributors to OpenNARS can we please have you agreement to change from GPL license to Apache?

@trevershick 
@jnorthrup 
@automenta 

Any issues or questions please let me know

**Comment by trevershick** [comment]
Agreed. Do you need something specifically?

**Comment by automenta** [comment]
https://www.gnu.org/philosophy/open-source-misses-the-point.html
https://digitizor.com/apache-license-vs-the-gpl/
https://www.fsf.org/bulletin/2016/fall/the-role-of-lawsuits-in-gpl-compliance
http://gpl-violations.org/faq/legal-faq/
![fjsjfldjlsjlsfcjlkjsdfkljdfksl](https://user-images.githubusercontent.com/157093/40331695-2acaa8c4-5d1f-11e8-89b5-462c85ccbb20.png)
:memo:

**Comment by PtrMan** [comment]
It's called Seth-style!

**Comment by TonyLo1** [comment]
@automenta thanks - I understand your position
