### ISSUE TITLE
NullPointerException with PART

### ISSUE THREAD

**Issue by PtrMan** [opennars/opennars#275]
(#,put,?1,into,?2)?

(#,put, the, function, a, into, function, b).

crashes

*log*
> LOG ConceptFire: DerivationContext[$0.87;0.45;1.00$ into,$0.6364;0.9000;1.0000$ $0.9000;0.9000;1.0000$ (#,put,?1,into,?2)?  {0 : 0} ]
> LOG Timing: 5
> LOG ConceptDirectProcessedTask: $0.2985;0.0300;0.1667$ (#,the,function,a,function,b)? 
> LOG TaskImmediateProcess: [$0.2985;0.0300;0.1667$ (#,the,function,a,function,b)? , DerivationContext[$0.15;0.03;0.17$ (#,the,function,a,function,b),null]]
> LOG TermLinkSelect: [_@(T2-2-3)(*,{SELF},(#,put,?1,into,?2)), $0.80;0.45;1.00$ into, DerivationContext[$0.80;0.45;1.00$ into,$0.6312;0.9000;1.0000$ $0.9000;0.9000;1.0000$ (#,put,?1,into,?2)?  {0 : 0} ]]
> LOG ConceptFire: DerivationContext[$0.80;0.45;1.00$ into,$0.6312;0.9000;1.0000$ $0.9000;0.9000;1.0000$ (#,put,?1,into,?2)?  {0 : 0} ]
> LOG Timing: 6
> LOG TaskDerive: [$0.3442;0.1000;0.9500$ (#,put,(#,the,function,a),into,function,b). %1.00;0.90% , false, true]
> LOG TaskAdd: [$0.3442;0.1000;0.9500$ (#,put,(#,the,function,a),into,function,b). %1.00;0.90% , Derived]
     (#,put,(#,the,function,a),into,function,b). %1.00;0.90% {6 : 1} 
> LOG TaskDerive: [$0.3994;0.0195;0.0950$ <put --> (/,#,_,the,function,a,into,function,b)>. %1.00;0.90% , false, true]
> LOG TaskAdd: [$0.3994;0.0195;0.0950$ <put --> (/,#,_,the,function,a,into,function,b)>. %1.00;0.90% , Derived]
     <put --> (/,#,_,the,function,a,into,function,b)>. %1.00;0.90% {6 : 1} 
> LOG TaskDerive: [$0.3999;0.1955;0.9050$ put. %1.00;0.81% , false, true]
> LOG TaskAdd: [$0.3999;0.1955;0.9050$ put. %1.00;0.81% , Derived]
     put. %1.00;0.81% {6 : 1} 
> LOG TermLinkSelect: [@(T1-1)_put, $0.73;0.50;0.95$ (#,put,the,function,a,into,function,b), DerivationContext[$0.73;0.50;0.95$ (#,put,the,function,a,into,function,b),$0.8000;0.5000;0.9500$ $0.8000;0.5000;0

crash

>java.lang.NullPointerException
>    at org.opennars.language.CompoundTerm.init (CompoundTerm.java:146)
>    at org.opennars.language.Conjunction.<init> (Conjunction.java:53)
>    at org.opennars.language.Conjunction.make (Conjunction.java:216)
>    at org.opennars.inference.StructuralRules.createSequenceTask (StructuralRules.java:717)
>    at org.opennars.inference.StructuralRules.groupSequence (StructuralRules.java:712)
>    at org.opennars.inference.StructuralRules.structuralCompound (StructuralRules.java:754)
>    at org.opennars.inference.RuleTables.compoundAndSelf (RuleTables.java:717)
>    at org.opennars.inference.RuleTables.applyRuleTable (RuleTables.java:118)
>    at org.opennars.inference.RuleTables.reason (RuleTables.java:108)
>    at org.opennars.control.GeneralInferenceControl.fireTermlink (GeneralInferenceControl.java:110)
>    at org.opennars.control.GeneralInferenceControl.fireTaskLink (GeneralInferenceControl.java:98)
>    at org.opennars.control.GeneralInferenceControl.fireConcept (GeneralInferenceControl.java:72)
>    at org.opennars.control.GeneralInferenceControl.selectConceptForInference (GeneralInferenceControl.java:53)
>    at org.opennars.storage.Memory.cycle (Memory.java:330)
>    at org.opennars.main.Nar.cycle (Nar.java:487)
>    at org.opennars.main.Nar.addMultiLineInput (Nar.java:221)
>    at org.opennars.main.Nar.addInput (Nar.java:266)
>...
>[WARNING] 
>java.lang.ArrayIndexOutOfBoundsException: 4
>    at org.opennars.inference.StructuralRules.groupSequence (StructuralRules.java:710)
>    at org.opennars.inference.StructuralRules.structuralCompound (StructuralRules.java:754)
>    at org.opennars.inference.RuleTables.compoundAndSelf (RuleTables.java:717)
>    at org.opennars.inference.RuleTables.applyRuleTable (RuleTables.java:118)
>    at org.opennars.inference.RuleTables.reason (RuleTables.java:108)
>    at org.opennars.control.GeneralInferenceControl.fireTermlink (GeneralInferenceControl.java:110)
>    at org.opennars.control.GeneralInferenceControl.fireTaskLink (GeneralInferenceControl.java:98)
>    at org.opennars.control.GeneralInferenceControl.fireConcept (GeneralInferenceControl.java:72)
>    at org.opennars.control.GeneralInferenceControl.selectConceptForInference (GeneralInferenceControl.java:53)
>    at org.opennars.storage.Memory.cycle (Memory.java:330)
>    at org.opennars.main.Nar.cycle (Nar.java:487)
>    at org.opennars.main.Nar.run (Nar.java:463)
>    at java.lang.Thread.run (Thread.java:844)

**Comment by PtrMan** [comment]
Don't worry - human level intelligence is far away because of this bugfest :smile:

**Comment by PtrMan** [comment]
[src](https://github.com/opennars/opennars/blob/master/src/main/java/org/opennars/inference/StructuralRules.java#L710) totalRight seems to be to small!

**Comment by PtrMan** [comment]
I think this part wasn't unittested - it's a good candidate, what do you think?

**Comment by patham9** [comment]
awesome find, will fix this today

**Comment by TonyLo1** [comment]
Good catch @PtrMan

**Comment by PtrMan** [comment]
Fixed https://github.com/opennars/opennars/pull/297
