### ISSUE TITLE
Clone

### ISSUE THREAD

**Issue by PtrMan** [opennars/opennars#283]
> <(*, fragmentA, fragmentB) --> disimilarityHigh> . :|: // the fragments are not similar enough
>
>10
>
><(*, {self}, fragmentA) --> mutate>. :|: // mutate
>
>10
>
><(*, fragmentA, fragmentB) --> compare >. :|: // compare
>
>
>
>
>50
>
><(*, fragmentC, fragmentD) --> disimilarityHigh> . :|: // the fragments are not similar enough
>
>10
>
><(*, {self}, fragmentC) --> mutate>. :|: // mutate
>
>10
>
><(*, fragmentC, fragmentD) --> compare >. :|: // compare
>
>
>50
>
>// ask about the variable assignment?
><(&/, ?30, ?20, <?50 --> disimilarityHigh>, +10, ?3, +10) =/> <(*, ?10, ?11) --> compare >>?

>org.opennars.language.CompoundTerm$UnableToCloneException: cloneDeepVariables resulted in >different class: <#varDep --> (|,(&,#1,disimilarityHigh),(&,#2,disimilarityHigh))> from (&&,<#varDep --> >(|,(&,#1,disimilarityHigh),(&,#2,disimilarityHigh))>,<#varDep --> (|,(&,#2,disimilarityHigh),(&,#1,disimilarityHigh))>)

**Comment by patham9** [comment]
Was already fixed by my stability PR: https://github.com/opennars/opennars/pull/290
