### ISSUE TITLE
Endless woundering bug (again)

### ISSUE THREAD

**Issue by PtrMan** [opennars/opennars#284]
><{(*, {self}, fragmentC)} --> mutate>. :|: // mutate
>
>10
>
><{(*, fragmentC, fragmentD)} --> compare >. :|: // compare
>
>
>50
>
>// ask about the variable assignment?
>\<?5 =/> \<?v --> compare >>?
>//<?v --> compare >?

Causes an endless woundering chain on NARS side :( . We need a unittest for this!

**Comment by patham9** [comment]
not reproducible. and doesn't sound like a bug but control mechanism property.

**Comment by PtrMan** [comment]
markdown messed up the Narsese because I need to get used to it

**Comment by PtrMan** [comment]
IN <{(*,{self},fragmentC)} --> mutate>. %1.00;0.90%
     <{(*,{self},fragmentC)} --> mutate>. %1.00;0.90%
     (--,<{(*,{self},fragmentC)} --> mutate>). %0.00;0.90%
     (--,<{(*,{self},fragmentC)} --> mutate>). %0.00;0.90%
     (--,<{(*,{self},fragmentC)} --> mutate>). %0.00;0.90%
     <{(*,{self},fragmentC)} --> mutate>. %1.00;0.90%
     <{(*,{self},fragmentC)} --> mutate>. %1.00;0.90%
     <{(*,{self},fragmentC)} --> mutate>. %1.00;0.90%
  IN <{(*,fragmentC,fragmentD)} --> compare>. %1.00;0.90%
     <{(*,fragmentC,fragmentD)} --> compare>. %1.00;0.90%
     (--,<{(*,fragmentC,fragmentD)} --> compare>). %0.00;0.90%
     (--,<{(*,fragmentC,fragmentD)} --> compare>). %0.00;0.90%
     (--,<{(*,fragmentC,fragmentD)} --> compare>). %0.00;0.90%
     <{(*,fragmentC,fragmentD)} --> compare>. %1.00;0.90%
     <{(*,fragmentC,fragmentD)} --> compare>. %1.00;0.90%
     <{(*,fragmentC,fragmentD)} --> compare>. %1.00;0.90%
  IN <?1 =/> <?2 --> compare>>?
     <?1 =/> <?2 --> compare>>?
     (^wonder,{SELF},<?1 =/> <?2 --> compare>>). :|: %1.00;0.90%
     <?1 --> compare>! %1.00;0.09%
     <?1 --> compare>! %1.00;0.09%
     <?1 =/> <?2 --> compare>>?
     <{(*,fragmentC,fragmentD)} --> compare>. %1.00;0.90%
     <{(*,fragmentC,fragmentD)} --> compare>. %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-30: %1.00;0.90%
     (--,(^wonder,{SELF},<?1 =/> <?2 --> compare>>)). :-42: %0.00;0.90%
     (--,(^wonder,{SELF},<?1 =/> <?2 --> compare>>)). :-42: %0.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-72: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-91: %1.00;0.90%
     (--,<?1 --> compare>)! %0.00;0.09%
     <?1 =/> (--,<?2 --> compare>)>?
     (--,<{(*,fragmentC,fragmentD)} --> compare>). %0.00;0.90%
     <{(*,fragmentC,fragmentD)} --> compare>. %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-125: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-128: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-146: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-160: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-172: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-181: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-197: %1.00;0.90%
     <?1 --> compare>! %1.00;0.09%
     <?1 --> compare>! %1.00;0.09%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-215: %1.00;0.90%
     <<?1 --> compare> =\> (--,?2)>?
     <<?1 --> compare> =\> (--,?2)>?
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-229: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-250: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-263: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-278: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-289: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-299: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-312: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-325: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-338: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-349: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-360: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-375: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-386: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-399: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-412: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-424: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-438: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-452: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-465: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-477: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-488: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-501: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-514: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-525: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-538: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-549: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-559: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-571: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-582: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-593: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-604: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-616: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-627: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-640: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-647: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-658: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-668: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-679: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-690: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-701: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-712: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-717: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-730: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-742: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-754: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-765: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-778: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-791: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-804: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-814: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-828: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-837: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-850: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-863: %1.00;0.90%
     <{SELF} --> (/,^wonder,_,<?1 =/> <?2 --> compare>>)>. :-875: %1.00;0.90%

**Comment by PtrMan** [comment]
We drown in - endless - ^wounder - and we are woundering till we die! :smile:

**Comment by patham9** [comment]
```
<(*,[valid],narsese) --> use>!
```
