### ISSUE TITLE
Shell command files not found

### ISSUE THREAD

**Issue by changbaishan** [opennars/opennars#298]
According to https://github.com/opennars/opennars, 
Command Shell Usage
You can launch NARS in several ways from command window (shell):

- empty reasoner (reads from stdin and writes to stdout):
    ./nars.sh

- gui (Swing)
    ./gui.sh [.nal input file]
    
- reasoner loaded from an experience file:
    ./nars.sh Examples/Example-NAL1-edited.txt --silence 90

- web server start for HTML GUI usage:
    ./web.sh 9999 localhost 9100 1000
     listen port^     ^IP    ^port ^time for each reasoning step in ms

However, these files were not included in the git distribution.

and 

nars_core - reasoning engine
nars_gui - java.swing GUI
nars_web - web server
nars_lab - experiments & demos
nars_test - unit tests
nal - examples

structure also not present.

**Comment by PtrMan** [comment]
This is outdated.

We just support maven for now

**Comment by PtrMan** [comment]
https://github.com/opennars/opennars/pull/299 Pullrequest(PR) is pending

**Comment by PtrMan** [comment]
I close this now because the PR should make it today or this early week.
