### ISSUE TITLE
Another NullPointerException with PART

### ISSUE THREAD

**Issue by PtrMan** [opennars/opennars#302]
> (#,put,?1,into,?2)?
> (#,put, the, function, a, into, function, b).

crashes

>java.lang.NullPointerException
>    at org.opennars.inference.StructuralRules.createSequenceTask (StructuralRules.java:755)
>    at org.opennars.inference.StructuralRules.createSequenceTaskByRange (StructuralRules.java:749)
>    at org.opennars.inference.StructuralRules.groupSequence (StructuralRules.java:699)
>    at org.opennars.inference.StructuralRules.structuralCompound (StructuralRules.java:790)
>    at org.opennars.inference.RuleTables.compoundAndSelf (RuleTables.java:721)
>    at org.opennars.inference.RuleTables.applyRuleTable (RuleTables.java:118)
>    at org.opennars.inference.RuleTables.reason (RuleTables.java:108)
>    at org.opennars.control.GeneralInferenceControl.fireTermlink (GeneralInferenceControl.java:110)
>    at org.opennars.control.GeneralInferenceControl.fireTaskLink (GeneralInferenceControl.java:98)
>    at org.opennars.control.GeneralInferenceControl.fireConcept (GeneralInferenceControl.java:72)
>    at org.opennars.control.GeneralInferenceControl.selectConceptForInference (GeneralInferenceControl.java:53)
>    at org.opennars.storage.Memory.cycle (Memory.java:330)
>    at org.opennars.main.Nar.cycle (Nar.java:486)
>    at org.opennars.main.Nar.run (Nar.java:462)
>    at java.lang.Thread.run (Thread.java:844)

**Comment by patham9** [comment]
fixed by https://github.com/opennars/opennars/pull/304
