### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by koo5** [opennars/opennars#31]
I want to use [Sourcegraph code search and code review](https://sourcegraph.com) with opennars. A project maintainer needs to enable it to set up a webhook so the code is up-to-date there.

Could you please enable opennars on @Sourcegraph by going to https://sourcegraph.com/github.com/opennars/opennars and clicking on Settings? (It should only take 15 seconds.)

Thank you!

**Comment by patham9** [comment]
"500 Internal Server Error
Something went wrong." Hm.

**Comment by automenta** [comment]
https://sourcegraph.com/github.com/opennars/opennars seems like its working now

**Comment by koo5** [comment]
yeah, im still not sure what it does but it seems to be working now
