### ISSUE TITLE
Input not parsed correctly

### ISSUE THREAD

**Issue by PtrMan** [opennars/opennars#325]
>(&/, < (&/, 41) --> (&/, 2) >).

(a bit of semantic nonsense)
>< [[10], (&/, 35)] =|> < 7 =/> 9 >>.
This one is transformed to
>  IN <(&|,7,[35,[10]]) =|> 9>. %1.00;0.90%

**Comment by PtrMan** [comment]
A whole new bug family

**Comment by PtrMan** [comment]
I suggest that we don't fix this for now and roll over all these issues with a real parser.

**Comment by patham9** [comment]
The transformation is correct, not a parser bug but a valid term reduction involving multiple ==>.

**Comment by PtrMan** [comment]
(&/, < (&/, 41) --> (&/, 2) >).

**Comment by PtrMan** [comment]
What about this one?

**Comment by PtrMan** [comment]
=/> and =\> is not ==>

**Comment by patham9** [comment]
=/> is indeed a form of implication.
```(&/, < (&/, 41) --> (&/, 2) >).``` works fine as I argued in the IRC.
