### ISSUE TITLE
HeapBag analysis and verification

### ISSUE THREAD

**Issue by automenta** [opennars/opennars#40]
HeapBag uses an iterative Heapsort which requires no allocation and accuracy (how many iterations performed, and when) is adjustable. It is most similar to CurveBag and uses the same type of curve function which is adjustable. However instead of CurveBag's insertion sort HeapBag swaps items into place, probably more efficiently than (and probably should replace) BubbleBag

**Comment by jnorthrup** [comment]
timing this one out.
