### ISSUE TITLE
"Multitask" Test Case Runner and Analysis

### ISSUE THREAD

**Issue by automenta** [opennars/opennars#41]
test framework for running combinations of test cases in parallel, for evaluating multitasking and attention focus abilities.

for example, if we know the performance of 2 different test cases, what is the performance of running them at the same time?  does it take 2x (assuming they involve mostly independent concerns) or does it take significantly more time?  does it need a memory 2x as large, or even more?  

measuring this will help tune scalabilty.

![screenshot_2015-06-04_20-27-59](https://cloud.githubusercontent.com/assets/157093/8017444/d4cce1da-0bc3-11e5-9a1c-6d6c93b7a207.png)

**Comment by jnorthrup** [comment]
restate for post-1.7 if applicable.
