### ISSUE TITLE
Memory is replicated between different NarNodes

### ISSUE THREAD

**Issue by PtrMan** [opennars/opennars#415]
Currently, the complete memory view is replicated 1:1 between all NarNode's.

A more advanced implementation should keep different subsets of Concepts in each NarNode.

**Comment by patham9** [comment]
Not at all:
1. only specified target nodes receive tasks.
2. Only tasks above target.priority are sent to the next node.
3. Only tasks that contain target.mustContainTerm are sent to the target.
