### ISSUE TITLE
Variable normalization causes wrong answers for Q&A

### ISSUE THREAD

**Issue by PtrMan** [opennars/opennars#488]
correct excepted answer \<(*,{tim},{tom}) --\> uncle\>. %1.00;0.73%

> IN <(&&,<#1 --> human>,<$2 --> (/,brother,,#1)>,<$3 --> (/,parent,#1,)>) ==> <(,$2,$3) --> uncle>>. %1.00;0.90%
> IN <{tim} --> human>. %1.00;0.90%
> IN <{tom} --> human>. %1.00;0.90%
> IN \<{john} --\> human\>. %1.00;0.90%
> IN \<{tom} --\> (/,parent,{john},)\>. %1.00;0.90%
> IN \<{tim} --\> (/,brother,,{john})\>. %1.00;0.90%
> IN \<(,{?1},{?2}) --\> uncle\>?
> Answer \<(*,{tim},{tim}) --\> uncle\>. %1.00;0.04%

it is caused by var normalization

workaround: make sure to name the vars in alphabetical order to circumvent

> \<(&&,\<(*,$1,#2) --\> brother\>,\<(*,#2,$3) --\> parent\>) ==\> \<(*,$1,$3) --\> uncle\>\>. %1.00;0.90%
> \<(*,{john},{tom}) --\> parent\>.
> \<(*,{tim},{john}) --\> brother\>.
> \<?what --> uncle\>?

**Comment by patham9** [comment]
see https://github.com/opennars/opennars/issues/489
