### ISSUE TITLE
Incorrect use of &/ as term for concept formation

### ISSUE THREAD

**Issue by TonyLo1** [opennars/opennars#496]
To reproduce:

a. :|:
b. :|:
a. :|:

open concept network window

concept with &/ term exists and has termlinks to multiple concepts
![bad concept term](https://user-images.githubusercontent.com/10548679/47568662-9adf1d80-d929-11e8-874a-630522b56f59.GIF)

**Comment by patham9** [comment]
These are not bugs. The intervals are normalized to +1. and the links to the components are normal termlinks.

**Comment by patham9** [comment]
If you mean that sequences should not be conceptualized at all, this is something we can discuss/add.
