### ISSUE TITLE
Allow an event to appear in pre and post conditions

### ISSUE THREAD

**Issue by TonyLo1** [opennars/opennars#501]
In order to support the following:
A. :|:
5
B. :|:
5
B. :|:
5

<(&/, A, ?1, B, ?2) =/> B>?

We need to relax this condition. This is required for event streams that have repeated events such as CISCO UC.

**Comment by patham9** [comment]
fixed by https://github.com/opennars/opennars/commit/f7d216d4d30f1f481b3ceac48ad680716c7077cc
