### ISSUE TITLE
in-parallel hypothesis testing for Decision Making

### ISSUE THREAD

**Issue by PtrMan** [opennars/opennars#502]
by patham9:
"I guess we need something new, some form of parallel hypothesis testing.
if only the used hypothesis is challenged, it can't fully make use of the feedback
when the used hypothesis gets downvoted by failed anticipation, it just switched to the next invalid hypothesis that was not yet downvoted!

The only way to make it succeed is to implement parallel hypothesis testing of k hypothesis, 1 is a too extreme case that isn't effective enough.

Also ANSNA will need it:
Assumption of failure should target all the hypotheses in the postcondition table that had the precondition fullfilled, meaning also the operation  that was chosen as the best one according to one of the entries in the table."

Explanation: When the system chooses an operation because of a memorized implication, and performs the decision, in case of the failed anticipation, also the other implications in the precondition table that had their precondition mostly fulfilled should receive the negative feedback.

Also: In v3.0.0 the policy was to try the specific variable-free implications first, and only if they can't lead to a decision of desire value above threshold, the general ones will be considered too. As an update, once parallel hypothesis testing is implemented, the general hypotheses should directly compete with the variable-free, this shouldn't be an issue then anymore.

**Comment by patham9** [comment]
This has been implemented already in v3.0.1_dev2 and was brought to perfection.
