### ISSUE TITLE
Bag: Priority not taken into account at remove time

### ISSUE THREAD

**Issue by PtrMan** [opennars/opennars#507]
Items of the lowest priority should leave the bag when the bag is full and other items are inserted.
This invariant is not accounted for in the current bag-handling and wasn't taken into account in all recent versions.
Is a issue because the priorities of the items "drift".

LevelBag from 3.0.0 (and before) and Pei's bag version are all affected.

Ex:
Implementation chose to remove a item with 0.38 priority even when it had plenty below 0.1.

**Comment by patham9** [comment]
we resolved that with popPushPop strategy, an item with 0.38 would go to a higher level instead of being removed now. it's now guaranteed that the removal happens from the lowest level at least. (guaranteeing that it will always be the lowest priority item would demand more changes)
