### ISSUE TITLE
Configkuration is always loaded from core

### ISSUE THREAD

**Issue by PtrMan** [opennars/opennars#545]
The configurations of neither lab nor applications are loaded - it instead loads always the configuration from OpenNARS.

**Comment by patham9** [comment]
Nope.
Starting Lab:
Loading config defaultConfig.xml from file
Starting Applications:
Loading config defaultConfig.xml from file

**Comment by PtrMan** [comment]
I was starting it from IDEA. No idea what you used here. Does it load it correctly when run with maven?

**Comment by patham9** [comment]
Yes should be. Just put the the file in the run directory under config, same as in the release zip and in the Application repo.

**Comment by patham9** [comment]
Starting applications in Netbeans:
Got relative path for loading the config: ./config/defaultConfig.xml
Loading config defaultConfig.xml from file
looks fine.

**Comment by patham9** [comment]
just tried with mvn exec:java -Dexec.mainClass="org.opennars.main.Shell":
Got relative path for loading the config: ./config/defaultConfig.xml
Loading config defaultConfig.xml from file
[l]: attaching Shell to Nar...
