### ISSUE TITLE
Task.EnumType naming

### ISSUE THREAD

**Issue by automenta** [opennars/opennars#555]
while it does make perfectly clear that it's an enum maybe its more useful to describe what it actually refers to.  Task.TaskType

unless its simpler just to subclass Task to InputTask and DerivedTask, and any other task types

**Comment by PtrMan** [comment]
Maybe Task.EnumTaskType, I was always using X.EnumType where Type refers to X (because it's a enum/sublcass).

Patrick can decide if he wants two more classes :D

**Comment by patham9** [comment]
You know I'm not a fan of introducing classes for such purposes. The next step would then be to add subclasses for RevisedTask, DeducedTask, InferredTask, ForgottenTask or whatever, I don't like Inheritance over-usage, and favor composition. A related question is whether we should keep "Enum" in EnumType, or whether we should just call it Type, but that's a different issue, so this one can be closed now.
