### ISSUE TITLE
Wiki Image Scratchpad

### ISSUE THREAD

**Issue by jnorthrup** [opennars/opennars#60]
**_scratchpad**_

github _issues_ allow image pasting.  github _wiki_ does not.  link things from _issues_ into the _wiki_ conveniently to host images.

the nars grammar
![image](https://cloud.githubusercontent.com/assets/73514/12365002/ece1d8e8-bb86-11e5-9ea3-b2cf5fb44292.png)

**Comment by jarradh** [comment]
I'll update the grammar once it's complete

**Comment by jnorthrup** [comment]
intellij grammarkit plugin wanted a few tweaks to get the parser into the intelij models.  below. 
//(* Narsese Grammar - https://github.com/opennars/opennars/wiki/Input-Output-Format *)

             task ::= [budget] sentence                                                                      //(* task to be processed *)

         sentence ::= statement"." [tense] [truth]                                                           //(* judgement to be remembered *)
                    | statement"?" [tense] [truth]                                                           //(* question to be answered, tense added in OpenNARS 1.7 *)
                    | statement"@" [tense] [truth]                                                           //(* question on desire value to be answered, tense added in OpenNARS 1.7 *)
                    | statement"!" [tense] [truth]                                                           //(* goal to be realized, tense added in OpenNARS 1.7 *)

           copula ::= "-->"                                                                                  //(* inheritance *)
                    | "<->"                                                                                  //(* similarity *)
                    | "{--"                                                                                  //(* instance *)
                    | "--]"                                                                                  //(* property *)
                    | "{-]"                                                                                  //(* instance-property *)
                    | "==>"                                                                                  //(* implication *)
                    | "=/>"                                                                                  //(* predictive implication *)
                    | "=|>"                                                                                  //(* concurrent implication *)
                    | "=\\>"                                                                                 //(* =\> retrospective implication *)
                    | "<=>"                                                                                  //(* equivalence *)
                    | "</>"                                                                                  //(* predictive equivalence *)
                    | "<|>"                                                                                  //(* concurrent equivalence *)

                                                                                         //(* a statement can serve as a term *)

    compound-term ::= "{" term {","term} "}"                                                                 //(* extensional set *)
                    | "[" term {","term} "]"                                                                 //(* intensional set *)
                    | "(&," term {","term} ")"                                                               //(* extensional intersection *)
                    | "(|," term {","term} ")"                                                               //(* intensional intersection *)
                    | "(-," term "," term ")"                                                                //(* extensional difference *)
                    | "(~," term "," term ")"                                                                //(* intensional difference *)
                    | "(*," term {","term} ")"                                                               //(* product *)
                    | "(" term {","term} ")"                                                                 //(* product, new notation *)
                    | "(/," term {","term} ")"                                                               //(* extensional image *)
                    | "(\\," term {","term} ")"                                                              //(* \ intensional image *)
                    | "(--," term ")"                                                                        //(* negation *)
                    | "--"term                                                                               //(* negation, new notation *)
                    | "(||," term {","term} ")"                                                              //(* disjunction *)
                    | "(&&," term {","term} ")"                                                              //(* conjunction *)
                    | "(&/," term {","term} ")"                                                              //(* sequential events *)
                    | "(&|," term {","term} ")"                                                              //(* parallel events *)

                    //(* new compound-term notation *)

                    | "(" term {infix-op-multi term} ")"                                                     //(* compound-term with infix operator *)
                    | "(" term infix-op-single term ")"

     infix-op-multi::= "&&"                                                                                  //(* conjunction *)
                    |  "*"                                                                                   //(* product *)
                    |  "||"                                                                                  //(* disjunction *)
                    |  "&|"                                                                                  //(* parallel events *)
                    |  "&/"                                                                                  //(* sequential events *)
                    |  "|"                                                                                   //(* intensional intersection *)
                    |  "&"                                                                                   //(* extensional intersection *)

    infix-op-single::= "-"                                                                                   //(* extensional difference *)
                    |  "~"                                                                                   //(* intensional difference *)

         variable ::= "$"word                                                                                //(* independent variable *)
                    | "#"[word]                                                                              //(* dependent variable *)
                    | "?"[word]                                                                              //(* query variable in question *)

            tense ::= ":/:"                                                                                  //(* future event *)
                    | ":|:"                                                                                  //(* present event *)
                    | ":\\:"                                                                                 //(* :\: past event *)
                    | ":" "\d+" ":"                                                                       //(* defined event, output only *)

            truth ::= <"%">frequency[<";">confidence]<"%">                                                   //(* two numbers in [0,1]x(0,1) *)
           budget ::= <"$">priority[<";">durability][<";">quality]<"$">                                      //(* three numbers in [0,1]x(0,1)x[0,1] *)

               word ::=  "\w+"
               term ::= word                                                                                   //(* an atomic constant term *)
                                           | variable                                                                               //(* an atomic variable term *)
                                           | compound-term                                                                          //(* a term with internal structure *)
                                           | statement
                               statement ::= "<" term copula term ">"                                                             //(* two terms related to each other *)
                                           | "(" term copula term ")"                                                             //(* two terms related to each other, new notation *)
                                           | term                                                                                   //(* a term can name a statement *)
                                           | "(^"word {","term} ")"                                                                 //(* an operation to be executed *)
                                           | word"("term {","term} ")"                                                              //(* an operation to be executed, new notation *)


                                                                                       //(* unicode string *)
           priority ::="([0]?\.[0-9]+|1|0)"                                                                  //(* 0 <= x <= 1 *)
         durability ::="[0]?\.[0]*[1-9]{1}[0-9]*"                                                            //(* 0 <  x <  1 *)
            quality ::="([0]?\.[0-9]+|1|0)"                                                                  //(* 0 <= x <= 1 *)
          frequency ::="([0]?\.[0-9]+|1|0)"                                                                  //(* 0 <= x <= 1 *)
         confidence ::="[0]?\.[0]*[1-9]{1}[0-9]*"                                                            //(* 0 <  x <  1 *)




this want to generate some parsers from your bnf, haven't clicked that yet
![image](https://cloud.githubusercontent.com/assets/73514/12365189/0fe20d58-bb88-11e5-86c0-9dca7c9c83c0.png)

**Comment by patham9** [comment]
![image](https://user-images.githubusercontent.com/8284677/45256886-b3d84300-b36a-11e8-8479-f0dfd8d3d8e4.png)

**Comment by patham9** [comment]
![image](https://user-images.githubusercontent.com/8284677/45256897-db2f1000-b36a-11e8-8daf-79b530809ad4.png)

**Comment by patham9** [comment]
![image](https://user-images.githubusercontent.com/8284677/45256919-4d075980-b36b-11e8-98c4-c028e87f1784.png)

**Comment by patham9** [comment]
![image](https://user-images.githubusercontent.com/8284677/45256932-893aba00-b36b-11e8-927a-06c0c3acf872.png)

**Comment by patham9** [comment]
![image](https://user-images.githubusercontent.com/8284677/45256939-c901a180-b36b-11e8-985b-a5a3cc32ba84.png)

**Comment by patham9** [comment]
![image](https://user-images.githubusercontent.com/8284677/45256951-049c6b80-b36c-11e8-8bfc-78baec482068.png)

**Comment by patham9** [comment]
![image](https://user-images.githubusercontent.com/8284677/45256980-4a593400-b36c-11e8-8243-75d8c65bc1c5.png)

**Comment by patham9** [comment]
![image](https://user-images.githubusercontent.com/8284677/45257017-dec39680-b36c-11e8-8d26-f84965c6f9e0.png)

**Comment by patham9** [comment]
![image](https://user-images.githubusercontent.com/8284677/45257040-4aa5ff00-b36d-11e8-8e2f-efe6d66a5a9f.png)

**Comment by pisaev1** [comment]
![image](https://user-images.githubusercontent.com/24262360/51793364-56b02300-218d-11e9-8a28-a0b71146b5d7.png)

**Comment by pisaev1** [comment]
![image](https://user-images.githubusercontent.com/24262360/52544538-64fe6180-2d7f-11e9-8ece-3e95c8c652ce.png)

**Comment by pisaev1** [comment]
![image](https://user-images.githubusercontent.com/24262360/52545458-ac87ec00-2d85-11e9-90de-8b2f18da6e4a.png)

**Comment by pisaev1** [comment]
![image](https://user-images.githubusercontent.com/24262360/52942696-732d1e80-3339-11e9-92bb-900f9e4a6536.png)

**Comment by pisaev1** [comment]
![image](https://user-images.githubusercontent.com/24262360/52943113-63620a00-333a-11e9-9adb-fbc175f8ed34.png)

**Comment by pisaev1** [comment]
![image](https://user-images.githubusercontent.com/24262360/52943282-ceabdc00-333a-11e9-8f9a-e4c6835ce953.png)

**Comment by patham9** [comment]
![grafik](https://user-images.githubusercontent.com/8284677/53459774-da7e5900-3a32-11e9-9d0b-c445250ef73a.png)

**Comment by patham9** [comment]
![grafik](https://user-images.githubusercontent.com/8284677/53459934-4660c180-3a33-11e9-8cfd-05f62aab52e8.png)

**Comment by patham9** [comment]
![grafik](https://user-images.githubusercontent.com/8284677/53459976-6ee8bb80-3a33-11e9-8ae4-2325fc587565.png)

**Comment by pisaev1** [comment]
![image](https://user-images.githubusercontent.com/24262360/54101472-439e8e80-439a-11e9-9eb1-f4b439703489.png)

**Comment by pisaev1** [comment]
![image](https://user-images.githubusercontent.com/24262360/54265424-a97e4800-454b-11e9-857e-eaa6ba5a20ff.png)

**Comment by pisaev1** [comment]
![image](https://user-images.githubusercontent.com/24262360/54265915-ba7b8900-454c-11e9-985a-cedc2d15bba1.png)

**Comment by pisaev1** [comment]
![image](https://user-images.githubusercontent.com/24262360/54455892-37685780-4733-11e9-839f-fd35dfea69ef.png)

**Comment by pisaev1** [comment]
![image](https://user-images.githubusercontent.com/24262360/60361446-2d99f580-99ac-11e9-8be1-0a118bc7ffc6.png)

**Comment by pisaev1** [comment]
![image](https://user-images.githubusercontent.com/24262360/60750092-a16e6c00-9f71-11e9-94bc-120cd7b225ab.png)

**Comment by pisaev1** [comment]
![image](https://user-images.githubusercontent.com/24262360/61977023-44d3ff00-afbb-11e9-8263-17551cab7adb.png)

**Comment by pisaev1** [comment]
![image](https://user-images.githubusercontent.com/24262360/61996593-d9923780-b063-11e9-9d9d-5eeaa332aeea.png)

**Comment by jnorthrup** [comment]
i' closing this issue and locking it, the notifications are disjoint with my github activities these days.  cheers guys.
