### ISSUE TITLE
Changes to Storage.Memory broke GUI build

### ISSUE THREAD

**Issue by TonyLo1** [opennars/opennars#601]
Opennars.gui build fails with following error. Appears to be related to recent change in opennars.opennars.storage.memory

[ERROR] /C:/Source/Repos/opennars-gui/src/main/java/org/opennars/gui/output/TaskTree.java:[187,25] cannot find symbol
  symbol:   variable newTasks
  location: variable mem of type org.opennars.storage.Memory

**Comment by patham9** [comment]
Good find! Hm this issue should be in opennars-gui, but it doesn't matter anymore now. Feel free to accept the GUI PR that fixes it: https://github.com/opennars/opennars-gui/pull/82

**Comment by patham9** [comment]
PR was merged yesterday already.
