### ISSUE TITLE
narsese parser can't parse ':' as a single symbol

### ISSUE THREAD

**Issue by AIxer** [opennars/opennars#617]
![image](https://user-images.githubusercontent.com/19511727/85974068-1ea6b280-ba07-11ea-84d6-61121097e43c.png)

**Comment by AIxer** [comment]
may be need an enhancement?

**Comment by PtrMan** [comment]
Improvement is unlikely. Just rewrite it as SEMICOLON or something like that.

I suspect that you try to feed tokens to NARS(ese) directly, this is not good. Just rewrite them as some other names **which do not use narsese symbols(!)**.

**Comment by AIxer** [comment]
I don't think this should be treated like avoid keywords in common programming languages, NARS in my sense should accept universal inputs.

**Comment by PtrMan** [comment]
I disagree. NARS is not a programming system. The language (narsese) isn't a programming system either. Some symbols like < > { } [ ] etc have a "special meaning"(to the parser), so they can't be used as term-names.

Yes there are some structural similarities between lets say narsese and SQL or prolog. But the story is extremely different under the hood.

**Comment by PtrMan** [comment]
The narsese parser may parse : as a valid term-name, that's right. But a workaround is easy to do.

**Comment by AIxer** [comment]
Yes, it can be a term, I should focus on the control part and inference process. 😄

**Comment by PtrMan** [comment]
gl hf

**Comment by patham9** [comment]
Terms are just identifiers, so in principle an implementation could even only allow [01]* (any sequence of 0's and 1's) to be used as atomic term, and it would still be fine.
