### ISSUE TITLE
Input channels (nars_core)

### ISSUE THREAD

**Issue by patham9** [opennars/opennars#79]
Some observations:
- Recent experiments show that NARS itself can be effective for perception processing:
https://groups.google.com/forum/#!topic/open-nars/pba2Mfyti0I
- Currently all input events enter event bag and are processed using the systems general purpose temporal inference control strategy. 

One one hand it should remain that all input comes from addInput(string); method,
but on the other hand not all input modalities can be processed by the general policy of event bag very effectively. That raises the question:
How to allow modality-specific control strategies, "custom channels" which only report their highest priority results into event bag, while being addressed by addInput without complicating the interface?

Idea:
Allow certain sensory input terms to be registered to go into a certain input channel.
These then don't enter NARS directly, but enter the custom channel instead, and are processed in that channel using a custom policy. The best results will be retrieved from the NARS instance automatically for transition to event bag.

**Comment by automenta** [comment]
https://github.com/automenta/narchy/blob/skynet5/nal/src/main/java/nars/control/CauseChannel.java#L17
https://github.com/automenta/narchy/blob/skynet5/nal/src/main/java/nars/NAR.java#L1646

https://github.com/automenta/narchy/blob/skynet5/nal/src/main/java/nars/control/Deriver.java#L57
https://github.com/automenta/narchy/blob/skynet5/app/src/main/java/nars/NAgentX.java#L192

**Comment by patham9** [comment]
I don't think that ensembles what we want besides that you also called it "Channel". Thanks anyways.

**Comment by automenta** [comment]
for reference

**Comment by patham9** [comment]
Already implemented. And the vision channel is already in development, not much missing anymore.
