### ISSUE TITLE
conditions and loops

### ISSUE THREAD

**Issue by PtrMan** [opennars/opennars#82]
Introduction of conditions and loops may be useful for high level thought processes or primitives of such.

Two basic primitives we already discussed are conditions and loops.

= Conditions

Conditions are used to feed goals depending on an assignment/value of a term (for example with a PART) ex:
(#, codepath, 0). // Path0 will be the goal

Switch is an op which emits a goal based on the assignment:

^switch(codepath, Path0, Path1, Path2)!

= Loops

ExecuteTimes(2,Op())!

in narsese:

<(*,{SELF},2,<(*,{SELF},blub) --> ^testop>) --> ^executeTimes>!

**Comment by PtrMan** [comment]
No idea how to manage an interaction of conditions and loops. For example a loop which calls an op which does an condition. Any ideas?

**Comment by pei2nars** [comment]
Loops are absolutely necessary for NARS, though the way to do it is
probably different from the procedural languages like C and Java.

My belief is that the for-loop type of iteration can be obtained mostly
from recursion, like in Prolog; the while-loop type of iteration can be
obtained directly from the repeated using of a conditional statement, like
in a production system.

It may also be necessary to explicitly introduce loops as a compound
operation, though I don't think it should be a primary form of iteration.

Regards,

Pei

**Comment by patham9** [comment]
I fully agree. 
And both mentioned forms are fully supported.
@PtrMan: But feel free to experiment with a mental-Op-based loop in nars_lab, to try the third idea.

**Comment by patham9** [comment]
And example to execute something 3 times using recursion:

`
<<(/,successor,$1,_) --> mycounter> ==> <$1 --> mycounter>>.
<(/,successor,(/,successor,0,_),_) --> mycounter>.
<<#1 --> mycounter> ==> (^want,{SELF},(^pick,{SELF},$1))>.
 EXE $0.05;0.00;0.83$ ^pick([{SELF}, (/,successor,0,_)])=null
 EXE $0.05;0.02;0.86$ ^pick([{SELF}, (/,successor,(/,successor,0,_),_)])=null
 EXE $0.02;0.00;0.68$ ^pick([{SELF}, (/,successor,(/,successor,(/,successor,0,_),_),_)])=null
`
