### ISSUE TITLE
Mavenize project and split into separate repositories.

### ISSUE THREAD

**Issue by freemo** [opennars/opennars#87]
The project should be split into separate logical repositories, core example nars_core and nars_web. Each one should be mavenized and the appropriate dependencies added between them.

**Comment by freemo** [comment]
nars core has now been mavenized and compiles successfully. Are there test classes for it somewhere I am missing? The pull request is up, just gotta add the test classes back...

**Comment by freemo** [comment]
@patham9 nars_core's unit tests depend on nars_lab, if nars_lab itself depends on nars_core then we have a problem. Ill see if there is any sort of quick fix.

**Comment by patham9** [comment]
Hm maybe there are some test-package-relevant classes in nars_lab. If that's the case they can probably just be moved to the test-part of nars_core as to remove their dependency on nars_lab. If this doesn't fix it, I guess only beer can! :)

**Comment by freemo** [comment]
yea im working on it.. there is some ugly stuff like some dependencies on
some stuff autmenta did but never released it to central.. just one file
though so with his permission ill move over the file itself.

**Comment by freemo** [comment]
@patham9 and @PtrMan The mavenization of core is ready, and working. Tests compile and run. One fails but likely not related to anything i did. We of course need to do some refactoring now, but ill leave that as a separate ticket. Otherwise look it over and make sure there are no issues. I will continue on mavenizing the other modules. Once we get it in ill retackle some of the other refactoring.

**Comment by freemo** [comment]
OpenNARS GUI is now mavenized and pulled out as a module as well. It can be found here: https://github.com/freemo/opennars-gui

**Comment by freemo** [comment]
OpenNARS web is now mavenized and ready here: https://github.com/freemo/opennars-web

**Comment by freemo** [comment]
OpenNARS lab now mavenized and ready here: https://github.com/freemo/opennars-lab

The entire project has now been mavenized

https://github.com/freemo/opennars
https://github.com/freemo/opennars-web
https://github.com/freemo/opennars-gui
https://github.com/freemo/opennars-lab

the pull request here: https://github.com/opennars/opennars/pull/106

Someone needs to find a new proper home for the docs (its own repo), the web client, and we probably want to add maven tasks to run the various components. But for the most part its ready to merge in. Someone obviously needs to create new repos for my forks too.

One final note since someone decided to use a snapshot/unreleased version of JBox2D you need to first clone JBox2D and install it locally (normally this would be handled as a dependency if it were a released version). You can get that here: https://github.com/jbox2d/jbox2d 

I will open a ticket encouraging us to migrate away from the snapshot of jbox2D

@patham9 @PtrMan please tag whoever can approve this stuff and get it in. I have a lot more work to do, so the sooner we get it in the sooner I can tackle some of the other tickets for you.

**Comment by freemo** [comment]
completed
