### ISSUE TITLE
Decide on one sentance byline for OpenNARS

### ISSUE THREAD

**Issue by freemo** [opennars/opennars#91]
Decide on a one sentance byline that describes OpenNARS. Set this as the description on GitHub and it will also be used in maven to describe the project and elsewhere such as in the pom and in the readme.

**Comment by TonyLo1** [comment]
An implementation of the Non-Axiomatic Reasoning System (NARS) - A General Machine Intelligence

**Comment by freemo** [comment]
thanks ill update based on this.
