### ISSUE TITLE
Add license headers to all files

### ISSUE THREAD

**Issue by freemo** [opennars/opennars#93]
Add the GPL license headers to all source files.

**Comment by patham9** [comment]
I vote for it if GPL requires it (is it?), else against it.

**Comment by freemo** [comment]
It is standard and expected for GPL and any other license, Since the condition of the license is that all copyright notices must be preserved if someone uses the code in their own project they are forced to retain the header. By not having it they woud be free to use the code without attributing the source and thus frowned upon on any copyleft license.

For more info: https://www.gnu.org/licenses/gpl-howto.en.html
