### ISSUE TITLE
Add all past and current developers to the POM as well as contributors file.

### ISSUE THREAD

**Issue by freemo** [opennars/opennars#96]
For now im just adding my own name to the pom and contributors file as a developer. We need to add all past developers however to ensure they get credit. The example line in the pom is as follows:

```
    <developers>
        <developer>
            <id>JeffreyPhillipsFreeman</id>
            <name>Jeffrey Phillips Freeman</name>
            <email>Jeffrey.Freeman@Syncleus.com</email>
            <url>http://JeffreyFreeman.me</url>
            <organization>Syncleus</organization>
            <organizationUrl>http://www.syncleus.com</organizationUrl>
            <roles>
                <role>Chief Technology Officer</role>
                <role>Project Owner</role>
                <role>Developer</role>
            </roles>
            <timezone>-5</timezone>
        </developer>
    </developers>
```

**Comment by TonyLo1** [comment]
Freemo - added
TonyLo1 - added
Patham9 - info required please (see template provided above)
PtrMan - info required please

Can people confirm the details and whether anyone is missing below:
Seth Horne <seh999@gmail.com> 
 jim <jim@cydesign.com> 
 tc <tc@box>

**Comment by freemo** [comment]
I can confirm seth's info. @automenta you happy about it?

**Comment by automenta** [comment]
((seh-->[developer]) && (((#dev-->[developer]), #it) --> [happy]))? :|:Android needs a narsese keyboard06.05.2018, 07:31, "Jeffrey Phillips Freeman" <notifications@github.com>:I can confirm seth's info. @automenta you happy about it?

**Comment by PtrMan** [comment]
<developer>
            <id>PtrMan</id>
            <name>Robert Wünsche</name>
            <email>robertw89@googlemail.com</email>
            <roles>
                <role>Developer</role>
            </roles>
            <timezone>+2</timezone>
        </developer>

**Comment by automenta** [comment]
please remove my entry from the file.  i never asked for it to appear and it violates my privacy.  comply with GDPR as well.

**Comment by automenta** [comment]
Art. 17 GDPR Right to erasure (‘right to be forgotten’)
https://gdpr-info.eu/art-17-gdpr/

**Comment by patham9** [comment]
tc@box was me, forgot to set a proper email in my TinyCore linux. :)

**Comment by patham9** [comment]
to fix the automenta issue: https://github.com/opennars/opennars/pull/215

**Comment by freemo** [comment]
@automenta The contact information added to the CONTRIBUTING file was placed there by automatically extracing it from the git log and placing it there. Your information can not be removed from git history since it is in the git logs itself and placed there by you. We can of course remove it from the CONTRIBUTING file, and im happy to do so, but just pointing out it is just redisplaying information about you that you yourself originally submited.

**Comment by automenta** [comment]
It is fine if my information just not appear in contrib and pom thank you06.05.2018, 22:13, "Jeffrey Phillips Freeman" <notifications@github.com>:@automenta The contact information added to the CONTRIBUTING file was placed there by automatically extracing it from the git log and placing it there. Your information can not be removed from git history since it is in the git logs itself and placed there by you. We can of course remove it from the CONTRIBUTING file, and im happy to do so, but just pointing out it is just redisplaying information about you that you yourself originally submited.

**Comment by PtrMan** [comment]
Any updates on this? We still need to do this before the official release

**Comment by patham9** [comment]
can you do it?

**Comment by patham9** [comment]
I did this already

**Comment by automenta** [comment]
Any nars release should be qualified by a confidence value.
12.0.3;25%

**Comment by automenta** [comment]
of course NARS can release NARS.  more officially than human :factory:
